services:
  demo:
    build:
      dockerfile: deployment/docker/infer.gpu.Dockerfile
    image: kryptonite-infer-gpu:local
    privileged: true
    command:
      - python
      - apps/api/main.py
      - --config
      - configs/deployment/infer-gpu.toml
      - --port
      - "8080"
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
