"""Serving adapters and backend wrappers."""

from .deployment import build_infer_artifact_report
from .enrollment_cache import (
    ENROLLMENT_CACHE_FORMAT_VERSION,
    build_enrollment_embedding_cache,
    load_enrollment_embedding_cache,
    validate_enrollment_cache_compatibility,
)
from .enrollment_store import (
    RUNTIME_ENROLLMENT_STORE_DB_NAME,
    RUNTIME_ENROLLMENT_STORE_FORMAT_VERSION,
    RuntimeEnrollmentStore,
)
from .http import create_http_app, create_http_server, run_http_server
from .inferencer import Inferencer
from .runtime import (
    ServeRuntimeReport,
    build_serve_runtime_report,
    build_service_metadata,
    render_serve_runtime_report,
)
from .scoring_service import EnrollmentNotFoundError, EnrollmentRecord, ScoringService
from .stress_report import (
    DEFAULT_BATCH_SIZES,
    DEFAULT_BENCHMARK_ITERATIONS,
    DEFAULT_VERIFY_THRESHOLD,
    DEFAULT_WARMUP_ITERATIONS,
    InferenceStressMemorySummary,
    InferenceStressReport,
    InferenceStressSummary,
    StressHardLimitSummary,
    WrittenInferenceStressReport,
    build_inference_stress_report,
    default_stress_report_output_root,
    generate_inference_stress_inputs,
    render_inference_stress_markdown,
    write_inference_stress_report,
)
from .stress_report import (
    REPORT_JSON_NAME as INFERENCE_STRESS_REPORT_JSON_NAME,
)
from .stress_report import (
    REPORT_MARKDOWN_NAME as INFERENCE_STRESS_REPORT_MARKDOWN_NAME,
)
from .submission_bundle import (
    SUBMISSION_BUNDLE_JSON_NAME,
    SUBMISSION_BUNDLE_MARKDOWN_NAME,
    SUBMISSION_BUNDLE_README_NAME,
    SUBMISSION_BUNDLE_RELEASE_FREEZE_JSON_NAME,
    SUBMISSION_BUNDLE_RELEASE_FREEZE_MARKDOWN_NAME,
    SUPPORTED_SUBMISSION_BUNDLE_MODES,
    ReleaseFreezeScope,
    SubmissionBundleArtifactRef,
    SubmissionBundleConfig,
    SubmissionBundleReleaseFreeze,
    SubmissionBundleReport,
    SubmissionBundleSummary,
    WrittenSubmissionBundle,
    build_submission_bundle,
    build_submission_bundle_source_report,
    load_submission_bundle_config,
    normalize_submission_bundle_mode,
    render_submission_bundle_markdown,
    render_submission_bundle_readme,
    render_submission_bundle_release_freeze_markdown,
    write_submission_bundle,
)
from .telemetry import PROMETHEUS_CONTENT_TYPE, ServiceTelemetry, resolve_model_version
from .triton_repository import (
    DEFAULT_TRITON_MODEL_NAME,
    DEFAULT_TRITON_REPOSITORY_ROOT,
    BuiltTritonModelRepository,
    TritonDynamicBatchingConfig,
    TritonRepositoryRequest,
    build_triton_model_repository,
    build_triton_repository_source_report,
)
from .triton_smoke import TritonSmokeResult, render_triton_smoke_result, run_triton_infer_smoke

__all__ = [
    "DEFAULT_BATCH_SIZES",
    "DEFAULT_BENCHMARK_ITERATIONS",
    "DEFAULT_TRITON_MODEL_NAME",
    "DEFAULT_TRITON_REPOSITORY_ROOT",
    "DEFAULT_VERIFY_THRESHOLD",
    "DEFAULT_WARMUP_ITERATIONS",
    "BuiltTritonModelRepository",
    "EnrollmentNotFoundError",
    "EnrollmentRecord",
    "Inferencer",
    "INFERENCE_STRESS_REPORT_JSON_NAME",
    "INFERENCE_STRESS_REPORT_MARKDOWN_NAME",
    "InferenceStressReport",
    "InferenceStressMemorySummary",
    "InferenceStressSummary",
    "ScoringService",
    "ENROLLMENT_CACHE_FORMAT_VERSION",
    "PROMETHEUS_CONTENT_TYPE",
    "ReleaseFreezeScope",
    "ServeRuntimeReport",
    "RUNTIME_ENROLLMENT_STORE_DB_NAME",
    "RUNTIME_ENROLLMENT_STORE_FORMAT_VERSION",
    "RuntimeEnrollmentStore",
    "ServiceTelemetry",
    "SUPPORTED_SUBMISSION_BUNDLE_MODES",
    "SUBMISSION_BUNDLE_JSON_NAME",
    "SUBMISSION_BUNDLE_MARKDOWN_NAME",
    "SUBMISSION_BUNDLE_README_NAME",
    "SUBMISSION_BUNDLE_RELEASE_FREEZE_JSON_NAME",
    "SUBMISSION_BUNDLE_RELEASE_FREEZE_MARKDOWN_NAME",
    "SubmissionBundleArtifactRef",
    "SubmissionBundleConfig",
    "SubmissionBundleReleaseFreeze",
    "SubmissionBundleReport",
    "SubmissionBundleSummary",
    "TritonDynamicBatchingConfig",
    "TritonRepositoryRequest",
    "TritonSmokeResult",
    "build_enrollment_embedding_cache",
    "build_infer_artifact_report",
    "build_inference_stress_report",
    "build_submission_bundle",
    "build_submission_bundle_source_report",
    "build_service_metadata",
    "build_serve_runtime_report",
    "build_triton_model_repository",
    "build_triton_repository_source_report",
    "create_http_server",
    "create_http_app",
    "default_stress_report_output_root",
    "generate_inference_stress_inputs",
    "load_enrollment_embedding_cache",
    "render_triton_smoke_result",
    "render_serve_runtime_report",
    "render_inference_stress_markdown",
    "render_submission_bundle_markdown",
    "render_submission_bundle_release_freeze_markdown",
    "render_submission_bundle_readme",
    "resolve_model_version",
    "run_triton_infer_smoke",
    "run_http_server",
    "StressHardLimitSummary",
    "validate_enrollment_cache_compatibility",
    "normalize_submission_bundle_mode",
    "load_submission_bundle_config",
    "write_submission_bundle",
    "write_inference_stress_report",
    "WrittenSubmissionBundle",
    "WrittenInferenceStressReport",
]
